### ISSUE TITLE
Short gamefreeze on squad marker mouse over / mouse out

### ISSUE THREAD

**Issue by Adanteh** [drakelinglabs/projectrealityarma3#198] opened 2016-06-04 20:33 UTC
### ArmA3 Version:
+ 1.60

### PRA3 Version:
+ 0.5.0.215

### Description:
+ After the mission was running for a while, doing mouse over on squad markers would freeze the game for a couple seconds. The same would happen on mouse out. 

### Steps to reproduce:
+ Play mission for a little
+ Mouse over squad marker
+ Move mouse way from squad marker

### Where did the issue occur?
+ Dedi MP

**Comment by simon84** [comment] 2016-06-14 00:07
Can't reproduce. Could be a problem with the empty groups. We keep an eye on this.

**Comment by simon84** [comment] 2016-06-25 13:55
Should be fixed now

**Closed by simon84** 2016-06-25 13:55 UTC
Labels: bug, can't reproduce, need more info
