### ISSUE TITLE
Crewman has no Overall

### ISSUE THREAD

**Issue by Montiemedia** [drakelinglabs/projectrealityarma3#391] opened 2016-10-31 20:01 UTC
Version from 2016-31-10 09:00 PM with Console CMD ["Crewman"] call PRA3_Kit_fnc_applyKit; the Crewman hast no Uniform/Overall! This variable I start local and Global!

**Comment by netfusion** [comment] 2016-10-31 20:35
Which faction did you play? NATO, CSAT or AAF?

**Comment by TomNedry** [comment] 2016-10-31 20:47
Tested on NATO & CSAT. Issue occured on NATO only...

**Comment by jokoho48** [comment] 2016-10-31 21:26
should be fixed. i accidentally used the wrong classname

**Comment by TomNedry** [comment] 2016-11-01 13:59
Tested and works as intended.

**Closed** 2016-11-01 13:59 UTC
Labels: bug
